# Generated by Django 4.1.1 on 2022-09-11 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginformation',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 14, 24, 54, 310269)),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='images/category'),
        ),
    ]
