# Generated by Django 4.1.1 on 2022-09-11 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_bookinginformation_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginformation',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 14, 28, 28, 720185)),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category'),
        ),
    ]
