# Generated by Django 4.1.1 on 2022-09-11 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_booked_booking_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='product_img', to='hotel.gallery'),
        ),
        migrations.AlterField(
            model_name='bookinginformation',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 25, 19, 365329)),
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/room'),
        ),
    ]
